# Generated by Django 5.2.1 on 2025-12-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='economicentity',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.economicentity')),
            ],
            options={
                'unique_together': {('entity', 'year', 'month')},
            },
        ),
    ]
