# Generated by Django 5.2.1 on 2026-01-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='finance.economicentity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to='finance.economicentity')),
            ],
            options={
                'verbose_name': 'Entity consolidation',
                'verbose_name_plural': 'Entity consolidations',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
