# Generated by Django 5.2.1 on 2026-01-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_economicentitylink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodclose',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AddField(
            model_name='periodclose',
            name='egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodclose',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodclose',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='periodclose',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_closes', to='finance.economicentity'),
        ),
    ]
