# Generated by Django 5.2.9 on 2026-01-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_category_options_transaction_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_system',
            new_name='is_transfer_root',
        ),
    ]
