# Generated by Django 5.2.1 on 2026-01-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Texto normalizado que debe aparecer en la descripción', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('confidence', models.PositiveSmallIntegerField(default=100, help_text='Prioridad de la regla (mayor = se aplica primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_rules', to='finance.category')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_rules', to='finance.economicentity')),
            ],
            options={
                'verbose_name': 'Regla de clasificación',
                'verbose_name_plural': 'Reglas de clasificación',
                'ordering': ['-confidence', 'pattern'],
                'unique_together': {('pattern', 'category')},
            },
        ),
    ]
