# Generated by Django 5.2.1 on 2026-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_transaction_category_alter_transaction_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='classification_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('rule', 'Regla')], max_length=20, null=True),
        ),
    ]
