"""uq_transaction add account_id

Revision ID: 03ef79f1c633
Revises: 625651994d1f
Create Date: 2026-06-19 18:05:43.690948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ef79f1c633'
down_revision: Union[str, Sequence[str], None] = '625651994d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_transaction'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_transaction', 'transactions', ['source_file', 'account_id', 'source_row', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction'), 'transactions', ['source_file', 'source_row', 'type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
