"""empty message

Revision ID: 07146077ff94
Revises: 64801d0fdd7e
Create Date: 2026-05-20 14:35:16.509304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07146077ff94'
down_revision: Union[str, Sequence[str], None] = '64801d0fdd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('invoice_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'invoice_id')
    # ### end Alembic commands ###
