"""add arca_tickets table

Revision ID: 0c6c7c54dc95
Revises: de0e8f0e3f1a
Create Date: 2026-08-26 12:23:34.437432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6c7c54dc95'
down_revision: Union[str, Sequence[str], None] = 'de0e8f0e3f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arca_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('env', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('sign', sa.Text(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env', 'service', name='uq_arca_ticket_env_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arca_tickets')
    # ### end Alembic commands ###
