"""add contact_id to import_rules

Revision ID: 0fdbbeaafa87
Revises: d981d423baee
Create Date: 2026-05-07 12:59:39.384288

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fdbbeaafa87"
down_revision: Union[str, Sequence[str], None] = "d981d423baee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_rules", sa.Column("contact_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "import_rules", "contacts", ["contact_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "import_rules", type_="foreignkey")
    op.drop_column("import_rules", "contact_id")
    # ### end Alembic commands ###
