"""empty message

Revision ID: 133de419f1c7
Revises: ecdb0bc0e89d
Create Date: 2026-06-18 13:31:29.986334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "133de419f1c7"
down_revision: Union[str, Sequence[str], None] = "ecdb0bc0e89d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_rules", sa.Column("account_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "import_rules", "accounts", ["account_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "import_rules", type_="foreignkey")
    op.drop_column("import_rules", "account_id")
    # ### end Alembic commands ###
