"""fix NC enums

Revision ID: 1550143cbac1
Revises: c065858cb7b5
Create Date: 2026-06-23 10:57:43.757768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1550143cbac1'
down_revision: Union[str, Sequence[str], None] = 'c065858cb7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE vouchertype ADD VALUE IF NOT EXISTS 'NCA'")
    op.execute("ALTER TYPE vouchertype ADD VALUE IF NOT EXISTS 'NCB'")
    op.execute("ALTER TYPE vouchertype ADD VALUE IF NOT EXISTS 'NCC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
