"""add_invoice_tributes_and_iva_aliquot

Revision ID: 2e6f75bec23f
Revises: 102e9b42f732
Create Date: 2026-05-27 09:23:58.613921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6f75bec23f'
down_revision: Union[str, Sequence[str], None] = '102e9b42f732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_tributes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('tribute_type', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ivaaliquot_type = sa.Enum('exempt', 'reduced', 'standard', 'higher', name='ivaaliquot')
    ivaaliquot_type.create(op.get_bind(), checkfirst=True)
    op.add_column('invoice_lines', sa.Column('iva_aliquot', sa.Enum('exempt', 'reduced', 'standard', 'higher', name='ivaaliquot'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_lines', 'iva_aliquot')
    sa.Enum(name='ivaaliquot').drop(op.get_bind(), checkfirst=True)
    op.drop_table('invoice_tributes')
    # ### end Alembic commands ###
