"""sale_line_id_on_delete_set_null

Revision ID: 3dac1fb75bec
Revises: 88392e8db1fc
Create Date: 2026-06-04 14:02:04.180584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac1fb75bec'
down_revision: Union[str, Sequence[str], None] = '88392e8db1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('serial_numbers_sale_line_id_fkey'), 'serial_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'serial_numbers', 'invoice_lines', ['sale_line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_numbers', type_='foreignkey')
    op.create_foreign_key(op.f('serial_numbers_sale_line_id_fkey'), 'serial_numbers', 'invoice_lines', ['sale_line_id'], ['id'])
    # ### end Alembic commands ###
