"""model Contact name field size

Revision ID: 3f26c3bbb1f9
Revises: aa79340b45a1
Create Date: 2026-07-23 20:00:28.235684

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f26c3bbb1f9"
down_revision: Union[str, Sequence[str], None] = "aa79340b45a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "name",
        existing_type=sa.VARCHAR(length=60),
        type_=sa.String(length=150),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "name",
        existing_type=sa.String(length=150),
        type_=sa.VARCHAR(length=60),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
