"""add products, invoices, invoice_lines, serial_numbers

Revision ID: 4603344d6003
Revises: e24878ada5dc
Create Date: 2026-05-17 11:36:36.820303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4603344d6003'
down_revision: Union[str, Sequence[str], None] = 'e24878ada5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('margin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_type', sa.Enum('purchase', 'sale', name='invoicetype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('formal', sa.Boolean(), nullable=False),
    sa.Column('tax_only', sa.Boolean(), nullable=False),
    sa.Column('voucher_type', sa.Enum('A', 'B', 'C', 'NC', 'ND', name='vouchertype'), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serial_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('available', 'sold', 'reserved', name='serialstatus'), nullable=False),
    sa.Column('purchase_line_id', sa.Uuid(), nullable=False),
    sa.Column('sale_line_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('modified_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['invoice_lines.id'], ),
    sa.ForeignKeyConstraint(['sale_line_id'], ['invoice_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('accounts', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'accounts', 'users', ['created_by'], ['id'])
    op.add_column('attachments', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('attachments', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'attachments', 'users', ['modified_by'], ['id'])
    op.add_column('categories', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('categories', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['modified_by'], ['id'])
    op.add_column('contacts', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('contacts', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'contacts', 'users', ['created_by'], ['id'])
    op.add_column('currencies', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('currencies', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'currencies', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'currencies', 'users', ['modified_by'], ['id'])
    op.add_column('entities', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('entities', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'entities', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'entities', 'users', ['modified_by'], ['id'])
    op.add_column('entity_memberships', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('entity_memberships', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'entity_memberships', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'entity_memberships', 'users', ['created_by'], ['id'])
    op.add_column('exchange_rates', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('exchange_rates', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'exchange_rates', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'exchange_rates', 'users', ['created_by'], ['id'])
    op.add_column('import_rules', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('import_rules', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'import_rules', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'import_rules', 'users', ['created_by'], ['id'])
    op.add_column('transactions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('modified_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'modified_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'modified_by')
    op.drop_column('transactions', 'created_by')
    op.drop_constraint(None, 'import_rules', type_='foreignkey')
    op.drop_constraint(None, 'import_rules', type_='foreignkey')
    op.drop_column('import_rules', 'modified_by')
    op.drop_column('import_rules', 'created_by')
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.drop_constraint(None, 'exchange_rates', type_='foreignkey')
    op.drop_column('exchange_rates', 'modified_by')
    op.drop_column('exchange_rates', 'created_by')
    op.drop_constraint(None, 'entity_memberships', type_='foreignkey')
    op.drop_constraint(None, 'entity_memberships', type_='foreignkey')
    op.drop_column('entity_memberships', 'modified_by')
    op.drop_column('entity_memberships', 'created_by')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'modified_by')
    op.drop_column('entities', 'created_by')
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_column('currencies', 'modified_by')
    op.drop_column('currencies', 'created_by')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'modified_by')
    op.drop_column('contacts', 'created_by')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'modified_by')
    op.drop_column('categories', 'created_by')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'modified_by')
    op.drop_column('attachments', 'created_by')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'modified_by')
    op.drop_column('accounts', 'created_by')
    op.drop_table('serial_numbers')
    op.drop_table('invoice_lines')
    op.drop_table('invoices')
    op.drop_table('products')
    # ### end Alembic commands ###
