"""m2m entity_fiscal_identity 

Revision ID: 47ef6af838a1
Revises: c71edbfe91e2
Create Date: 2026-07-29 20:14:50.028374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ef6af838a1'
down_revision: Union[str, Sequence[str], None] = 'c71edbfe91e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_fiscal_identities',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_identity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['fiscal_identity_id'], ['fiscal_identities.id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'fiscal_identity_id')
    )
    op.execute(
    "INSERT INTO entity_fiscal_identities (entity_id, fiscal_identity_id) "
    "SELECT entity_id, id FROM fiscal_identities"
    )
    op.drop_constraint(op.f('fiscal_identities_entity_id_fkey'), 'fiscal_identities', type_='foreignkey')
    op.drop_column('fiscal_identities', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fiscal_identities', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fiscal_identities_entity_id_fkey'), 'fiscal_identities', 'entities', ['entity_id'], ['id'])
    op.drop_table('entity_fiscal_identities')
    # ### end Alembic commands ###
