"""currency.is_index for currency report conversion

Revision ID: 4af734ae01ae
Revises: f7844d7e6a68
Create Date: 2026-06-30 16:52:28.090006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af734ae01ae'
down_revision: Union[str, Sequence[str], None] = 'f7844d7e6a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('is_index', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'is_index')
    # ### end Alembic commands ###
