"""add ondelte layers DB and ORM 

Revision ID: 50ba3af0b575
Revises: aa4896d3e0c3
Create Date: 2026-06-22 20:36:51.302785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ba3af0b575'
down_revision: Union[str, Sequence[str], None] = 'aa4896d3e0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('import_rows_batch_id_fkey'), 'import_rows', type_='foreignkey')
    op.create_foreign_key('import_rows_batch_id_fkey', 'import_rows', 'import_batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transactions_import_batch_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_import_row_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_import_batch_id_fkey', 'transactions', 'import_batches', ['import_batch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_import_row_id_fkey', 'transactions', 'import_rows', ['import_row_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_import_row_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_import_batch_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_import_row_id_fkey'), 'transactions', 'import_rows', ['import_row_id'], ['id'])
    op.create_foreign_key(op.f('transactions_import_batch_id_fkey'), 'transactions', 'import_batches', ['import_batch_id'], ['id'])
    op.drop_constraint('import_rows_batch_id_fkey', 'import_rows', type_='foreignkey')
    op.create_foreign_key(op.f('import_rows_batch_id_fkey'), 'import_rows', 'import_batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###
