"""move attachment to invoice

Revision ID: 528adb80a152
Revises: 50ba3af0b575
Create Date: 2026-06-22 21:20:42.465802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528adb80a152'
down_revision: Union[str, Sequence[str], None] = '50ba3af0b575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('invoice_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('attachments_transaction_id_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_invoice_id_fkey', 'attachments', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('attachments', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('attachments_invoice_id_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_transaction_id_fkey'), 'attachments', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('attachments', 'invoice_id')
    # ### end Alembic commands ###
