"""add email identity to entities

Revision ID: 54b69e76dda6
Revises: 0c6c7c54dc95
Create Date: 2026-08-26 12:28:11.219704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b69e76dda6'
down_revision: Union[str, Sequence[str], None] = '0c6c7c54dc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('email_display_name', sa.String(length=100), nullable=True))
    op.add_column('entities', sa.Column('email_reply_to', sa.String(length=150), nullable=True))
    op.add_column('entities', sa.Column('email_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'email_signature')
    op.drop_column('entities', 'email_reply_to')
    op.drop_column('entities', 'email_display_name')
    # ### end Alembic commands ###
