"""remove currency_id from transactions

Revision ID: 6019e2466625
Revises: bd277852790b
Create Date: 2026-05-11 16:59:30.797716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6019e2466625'
down_revision: Union[str, Sequence[str], None] = 'bd277852790b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_parent_id_name'), 'categories', type_='unique')
    op.create_unique_constraint('uq_parent_id_name', 'categories', ['parent_id', 'name'])
    op.drop_column('import_rules', 'applied')
    op.drop_constraint(op.f('transactions_currency_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'currency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('transactions_currency_id_fkey'), 'transactions', 'currencies', ['currency_id'], ['id'])
    op.add_column('import_rules', sa.Column('applied', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint('uq_parent_id_name', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_parent_id_name'), 'categories', ['parent_id', 'name'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###
