"""empty message

Revision ID: 625651994d1f
Revises: 133de419f1c7
Create Date: 2026-06-19 14:25:55.328604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625651994d1f'
down_revision: Union[str, Sequence[str], None] = '133de419f1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_rows', 'reason',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_rows', 'reason',
               nullable=True)
    # ### end Alembic commands ###
