"""add_category_to_invoices

Revision ID: 64801d0fdd7e
Revises: 47803ff107e1
Create Date: 2026-05-20 11:33:43.480492

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64801d0fdd7e"
down_revision: Union[str, Sequence[str], None] = "47803ff107e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "invoices", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoices", type_="foreignkey")
    op.drop_column("invoices", "category_id")
    # ### end Alembic commands ###
