"""del  import_rule_tolerance_pct

Revision ID: 70801b890ab7
Revises: 790e1531278f
Create Date: 2026-06-12 16:59:51.679154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70801b890ab7"
down_revision: Union[str, Sequence[str], None] = "790e1531278f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_configs", "import_rule_tolerance_pct")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_configs",
        sa.Column(
            "import_rule_tolerance_pct",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            server_default=sa.text("10"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
