"""UQ Exchange_rate

Revision ID: 737a46e7815f
Revises: 7d849ccb3e19
Create Date: 2026-06-25 08:20:38.718725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737a46e7815f'
down_revision: Union[str, Sequence[str], None] = '7d849ccb3e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exchange_rate', 'exchange_rates', ['currency_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exchange_rate', 'exchange_rates', type_='unique')
    # ### end Alembic commands ###
