"""del min/max_amount in ImportRule, add source_file source_row in Transaction

Revision ID: 790e1531278f
Revises: c23dc0313c1e
Create Date: 2026-06-11 20:04:57.117063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790e1531278f'
down_revision: Union[str, Sequence[str], None] = 'c23dc0313c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_import_rule_pattern_type', 'import_rules', ['pattern', 'transaction_type'])
    op.drop_column('import_rules', 'min_amount')
    op.drop_column('import_rules', 'max_amount')
    op.add_column('transactions', sa.Column('source_file', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('source_row', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_transaction'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_transaction', 'transactions', ['source_file', 'source_row', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction'), 'transactions', ['account_id', 'date', 'description', 'amount', 'type'], postgresql_nulls_not_distinct=False)
    op.drop_column('transactions', 'source_row')
    op.drop_column('transactions', 'source_file')
    op.add_column('import_rules', sa.Column('max_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('999999999.99'), autoincrement=False, nullable=False))
    op.add_column('import_rules', sa.Column('min_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_import_rule_pattern_type', 'import_rules', type_='unique')
    # ### end Alembic commands ###
