"""add app_confige model

Revision ID: 7b320e1e468f
Revises: 87abc42e9d85
Create Date: 2026-06-06 20:35:53.209581

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b320e1e468f"
down_revision: Union[str, Sequence[str], None] = "87abc42e9d85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_rule_tolerance_pct", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_app_config_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("INSERT INTO app_configs (id, import_rule_tolerance_pct) VALUES (1, 10.00)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_configs")
    # ### end Alembic commands ###
