"""Entity.iibb_rate added

Revision ID: 7d849ccb3e19
Revises: 1550143cbac1
Create Date: 2026-06-24 00:42:46.413967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d849ccb3e19"
down_revision: Union[str, Sequence[str], None] = "1550143cbac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entities",
        sa.Column(
            "iibb_rate", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entities", "iibb_rate")
    # ### end Alembic commands ###
