"""cuit size changed

Revision ID: 87a6b1049cc2
Revises: 4af734ae01ae
Create Date: 2026-07-17 11:00:18.873985

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87a6b1049cc2"
down_revision: Union[str, Sequence[str], None] = "4af734ae01ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE contacts SET tax_id = regexp_replace(tax_id, '[^0-9]', '', 'g') WHERE tax_id IS NOT NULL"
    )
    op.alter_column(
        "contacts",
        "tax_id",
        existing_type=sa.VARCHAR(length=13),
        type_=sa.String(length=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "tax_id",
        existing_type=sa.String(length=11),
        type_=sa.VARCHAR(length=13),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
