"""import_rules unique pattern+type

Revision ID: 87abc42e9d85
Revises: 918748a78008
Create Date: 2026-06-06 18:27:53.551331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87abc42e9d85'
down_revision: Union[str, Sequence[str], None] = '918748a78008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('import_rules_pattern_key'), 'import_rules', type_='unique')
    op.create_unique_constraint('uq_import_rules_pattern_type', 'import_rules', ['pattern', 'transaction_type'])
    op.drop_constraint(op.f('fk_transaction_applied_rule_id'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'import_rules', ['applied_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_applied_rule_id'), 'transactions', 'import_rules', ['applied_rule_id'], ['id'])
    op.drop_constraint('uq_import_rules_pattern_type', 'import_rules', type_='unique')
    op.create_unique_constraint(op.f('import_rules_pattern_key'), 'import_rules', ['pattern'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
