"""serial_number_unique

Revision ID: 88df471ee022
Revises: b8222b5e598b
Create Date: 2026-06-03 22:22:35.277293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88df471ee022'
down_revision: Union[str, Sequence[str], None] = 'b8222b5e598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'serial_numbers', ['serial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial_numbers', type_='unique')
    # ### end Alembic commands ###
