"""add role and share to entity_membership

Revision ID: 918748a78008
Revises: 3dac1fb75bec
Create Date: 2026-06-05 12:43:13.691488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918748a78008'
down_revision: Union[str, Sequence[str], None] = '3dac1fb75bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_memberships', sa.Column('share', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_memberships', 'share')
    # ### end Alembic commands ###
