"""model invoice, added NC reference / relationshipn

Revision ID: 9776915e3b74
Revises: 194d0f0a9da5
Create Date: 2026-07-25 19:20:57.931691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9776915e3b74"
down_revision: Union[str, Sequence[str], None] = "194d0f0a9da5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("related_invoice_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_invoices_related_invoice_id", "invoices", "invoices", ["related_invoice_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "related_invoice_id")
    # ### end Alembic commands ###
