"""empty message

Revision ID: 9e8cf1ba33c4
Revises: 0fdbbeaafa87
Create Date: 2026-05-08 10:08:12.585489

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e8cf1ba33c4"
down_revision: Union[str, Sequence[str], None] = "0fdbbeaafa87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DELETE FROM import_rules")
    op.add_column(
        "import_rules",
        sa.Column(
            "transaction_type",
            sa.Enum("income", "expense", "transfer", name="transactiontype"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_rules", "transaction_type")
    # ### end Alembic commands ###
