"""add source_sheet uq

Revision ID: aa4896d3e0c3
Revises: 03ef79f1c633
Create Date: 2026-06-20 16:41:28.081904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4896d3e0c3'
down_revision: Union[str, Sequence[str], None] = '03ef79f1c633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source_sheet', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_transaction'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_transaction', 'transactions', ['source_file', 'source_sheet', 'source_row', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction'), 'transactions', ['source_file', 'account_id', 'source_row', 'type'], postgresql_nulls_not_distinct=False)
    op.drop_column('transactions', 'source_sheet')
    # ### end Alembic commands ###
