"""ARCA entity and contact fields for invoice PDF added

Revision ID: aa79340b45a1
Revises: c47b1f5bbdf9
Create Date: 2026-07-23 16:47:06.116921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa79340b45a1"
down_revision: Union[str, Sequence[str], None] = "c47b1f5bbdf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("address", sa.String(length=200), nullable=True))
    op.add_column("entities", sa.Column("address", sa.String(length=200), nullable=True))
    op.add_column("entities", sa.Column("iibb", sa.String(length=50), nullable=True))
    op.add_column("entities", sa.Column("start_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entities", "start_date")
    op.drop_column("entities", "iibb")
    op.drop_column("entities", "address")
    op.drop_column("contacts", "address")
    # ### end Alembic commands ###
