"""replace status with confirmed paid authorized

Revision ID: aff13a39d0f7
Revises: 37cf3e3c3e8b
Create Date: 2026-05-30 16:11:53.740113

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aff13a39d0f7"
down_revision: Union[str, Sequence[str], None] = "37cf3e3c3e8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("confirmed", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column(
        "invoices", sa.Column("paid", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column(
        "invoices", sa.Column("authorized", sa.Boolean(), nullable=False, server_default="false")
    )
    op.drop_column("invoices", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column(
            "status",
            postgresql.ENUM("pending", "authorized", "paid", "draft", name="voucherstatus"),
            server_default=sa.text("'pending'::voucherstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("invoices", "authorized")
    op.drop_column("invoices", "paid")
    op.drop_column("invoices", "confirmed")
    # ### end Alembic commands ###
