"""serial numbers added

Revision ID: b8222b5e598b
Revises: 7db2b6dbf29a
Create Date: 2026-06-03 11:15:34.393826

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8222b5e598b"
down_revision: Union[str, Sequence[str], None] = "7db2b6dbf29a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("track_serial", sa.Boolean(), nullable=False, server_default="false")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "track_serial")
    # ### end Alembic commands ###
