"""add category parent

Revision ID: b860930a7c70
Revises: 1f1aa8bbf3a8
Create Date: 2026-05-03 10:47:58.796933

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b860930a7c70"
down_revision: Union[str, Sequence[str], None] = "1f1aa8bbf3a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.drop_constraint(op.f("categories_name_key"), "categories", type_="unique")
    op.create_unique_constraint("uq_parent_id_name", "categories", ["parent_id", "name"])
    op.create_foreign_key(
        "fk_category_parent_id", "categories", "categories", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_category_parent_id", "categories", type_="foreignkey")
    op.drop_constraint("uq_parent_id_name", "categories", type_="unique")
    op.create_unique_constraint(
        op.f("categories_name_key"), "categories", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###
