"""invoice_line.iva_rate added

Revision ID: c065858cb7b5
Revises: 528adb80a152
Create Date: 2026-06-22 22:50:56.243181

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c065858cb7b5"
down_revision: Union[str, Sequence[str], None] = "528adb80a152"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoice_lines", sa.Column("iva_rate", sa.Numeric(precision=5, scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice_lines", "iva_rate")
    # ### end Alembic commands ###
