"""add cascade delete to invoice lines and tributes

Revision ID: c1fbbec91896
Revises: aff13a39d0f7
Create Date: 2026-05-30 16:45:30.225497

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1fbbec91896"
down_revision: Union[str, Sequence[str], None] = "aff13a39d0f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("invoice_lines_invoice_id_fkey"), "invoice_lines", type_="foreignkey")
    op.create_foreign_key(
        None, "invoice_lines", "invoices", ["invoice_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("invoice_tributes_invoice_id_fkey"), "invoice_tributes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "invoice_tributes", "invoices", ["invoice_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invoice_tributes", type_="foreignkey")
    op.create_foreign_key(
        op.f("invoice_tributes_invoice_id_fkey"),
        "invoice_tributes",
        "invoices",
        ["invoice_id"],
        ["id"],
    )
    op.drop_constraint(None, "invoice_lines", type_="foreignkey")
    op.create_foreign_key(
        op.f("invoice_lines_invoice_id_fkey"), "invoice_lines", "invoices", ["invoice_id"], ["id"]
    )
    # ### end Alembic commands ###
