"""add amount range to import rules

Revision ID: c23dc0313c1e
Revises: 7b320e1e468f
Create Date: 2026-06-06 20:45:33.488176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23dc0313c1e'
down_revision: Union[str, Sequence[str], None] = '7b320e1e468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_rules', sa.Column('min_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('import_rules', sa.Column('max_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='999999999.99'))
    op.drop_constraint(op.f('uq_import_rules_pattern_type'), 'import_rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_import_rules_pattern_type'), 'import_rules', ['pattern', 'transaction_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('import_rules', 'max_amount')
    op.drop_column('import_rules', 'min_amount')
    # ### end Alembic commands ###
