"""concepto, from_date, to_date, due_date added

Revision ID: c47b1f5bbdf9
Revises: 87a6b1049cc2
Create Date: 2026-07-22 12:28:33.998543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c47b1f5bbdf9"
down_revision: Union[str, Sequence[str], None] = "87a6b1049cc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("products", "services", "both", name="concepto").create(op.get_bind(), checkfirst=True)
    op.add_column(
        "invoices",
        sa.Column(
            "concepto",
            sa.Enum("products", "services", "both", name="concepto"),
            server_default="products",
            nullable=False,
        ),
    )
    op.add_column("invoices", sa.Column("from_date", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("to_date", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("due_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "due_date")
    op.drop_column("invoices", "to_date")
    op.drop_column("invoices", "from_date")
    op.drop_column("invoices", "concepto")
    sa.Enum(name="concepto").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
