"""add_condicion_iva_and_doc_type_to_contacts_entities

Revision ID: cf0357124647
Revises: 2e6f75bec23f
Create Date: 2026-05-28 13:58:41.503302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0357124647'
down_revision: Union[str, Sequence[str], None] = '2e6f75bec23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    condicioniva_type = sa.Enum('INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO', name='condicioniva')
    condicioniva_type.create(op.get_bind(), checkfirst=True)

    doctype_type = sa.Enum('CUIT', 'CUIL', 'DNI', 'FINAL', name='doctype')
    doctype_type.create(op.get_bind(), checkfirst=True)

    op.add_column('contacts', sa.Column('condicion_iva', sa.Enum('INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO', name='condicioniva'), nullable=False))
    op.add_column('contacts', sa.Column('doc_type', sa.Enum('CUIT', 'CUIL', 'DNI', 'FINAL', name='doctype'), nullable=False))
    op.add_column('entities', sa.Column('condicion_iva', sa.Enum('INSCRIPTO', 'EXENTO', 'FINAL', 'MONOTRIBUTO', name='condicioniva'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'condicion_iva')
    op.drop_column('contacts', 'doc_type')
    op.drop_column('contacts', 'condicion_iva')
    sa.Enum(name='condicioniva').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='doctype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
