"""add_email_to_contacts

Revision ID: d354674a5892
Revises: 07146077ff94
Create Date: 2026-05-20 19:41:25.287776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd354674a5892'
down_revision: Union[str, Sequence[str], None] = '07146077ff94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(length=254), nullable=True))
    op.drop_column('invoices', 'cuit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cuit', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
