"""add trade_name to contacts

Revision ID: de0e8f0e3f1a
Revises: 47ef6af838a1
Create Date: 2026-08-26 05:02:43.041299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0e8f0e3f1a'
down_revision: Union[str, Sequence[str], None] = '47ef6af838a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('trade_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'trade_name')
    # ### end Alembic commands ###
